// Generated by gencpp from file rsm_msgs/AddWaypointRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_ADDWAYPOINTREQUEST_H
#define RSM_MSGS_MESSAGE_ADDWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rsm_msgs/Waypoint.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct AddWaypointRequest_
{
  typedef AddWaypointRequest_<ContainerAllocator> Type;

  AddWaypointRequest_()
    : waypoint()
    , position(0)  {
    }
  AddWaypointRequest_(const ContainerAllocator& _alloc)
    : waypoint(_alloc)
    , position(0)  {
  (void)_alloc;
    }



   typedef  ::rsm_msgs::Waypoint_<ContainerAllocator>  _waypoint_type;
  _waypoint_type waypoint;

   typedef int64_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddWaypointRequest_

typedef ::rsm_msgs::AddWaypointRequest_<std::allocator<void> > AddWaypointRequest;

typedef boost::shared_ptr< ::rsm_msgs::AddWaypointRequest > AddWaypointRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::AddWaypointRequest const> AddWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.waypoint == rhs.waypoint &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23c630e1c4e5124218665574a9f6ebc8";
  }

  static const char* value(const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23c630e1c4e51242ULL;
  static const uint64_t static_value2 = 0x18665574a9f6ebc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/AddWaypointRequest";
  }

  static const char* value(const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/Waypoint waypoint # Waypoint to be added\n"
"int64 position                      # Position in array where to add waypoint (-1 defaults to end of array)\n"
"\n"
"================================================================================\n"
"MSG: rsm_msgs/Waypoint\n"
"#A waypoint for waypoint following\n"
"geometry_msgs/Pose pose     # Pose of this waypoint\n"
"bool visited                # True if the waypoint was already visited\n"
"bool unreachable			# True if no path to this waypoint could be found\n"
"string routine				# Routine to be executed on reaching waypoint\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoint);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::AddWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::AddWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "waypoint: ";
    s << std::endl;
    Printer< ::rsm_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "  ", v.waypoint);
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_ADDWAYPOINTREQUEST_H
