// Generated by gencpp from file rsm_msgs/AddWaypoint.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_ADDWAYPOINT_H
#define RSM_MSGS_MESSAGE_ADDWAYPOINT_H

#include <ros/service_traits.h>


#include <rsm_msgs/AddWaypointRequest.h>
#include <rsm_msgs/AddWaypointResponse.h>


namespace rsm_msgs
{

struct AddWaypoint
{

typedef AddWaypointRequest Request;
typedef AddWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddWaypoint
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::AddWaypoint > {
  static const char* value()
  {
    return "d88eb2b30f47caccaa78915d02fcd7a0";
  }

  static const char* value(const ::rsm_msgs::AddWaypoint&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::AddWaypoint > {
  static const char* value()
  {
    return "rsm_msgs/AddWaypoint";
  }

  static const char* value(const ::rsm_msgs::AddWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::AddWaypointRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::AddWaypoint >
template<>
struct MD5Sum< ::rsm_msgs::AddWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::AddWaypointRequest> should match
// service_traits::DataType< ::rsm_msgs::AddWaypoint >
template<>
struct DataType< ::rsm_msgs::AddWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::AddWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::AddWaypointResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::AddWaypoint >
template<>
struct MD5Sum< ::rsm_msgs::AddWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::AddWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::AddWaypointResponse> should match
// service_traits::DataType< ::rsm_msgs::AddWaypoint >
template<>
struct DataType< ::rsm_msgs::AddWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::AddWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::AddWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_ADDWAYPOINT_H
