// Generated by gencpp from file rsm_msgs/AddWaypointResponse.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_ADDWAYPOINTRESPONSE_H
#define RSM_MSGS_MESSAGE_ADDWAYPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsm_msgs
{
template <class ContainerAllocator>
struct AddWaypointResponse_
{
  typedef AddWaypointResponse_<ContainerAllocator> Type;

  AddWaypointResponse_()
    : success(false)
    , message()  {
    }
  AddWaypointResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddWaypointResponse_

typedef ::rsm_msgs::AddWaypointResponse_<std::allocator<void> > AddWaypointResponse;

typedef boost::shared_ptr< ::rsm_msgs::AddWaypointResponse > AddWaypointResponsePtr;
typedef boost::shared_ptr< ::rsm_msgs::AddWaypointResponse const> AddWaypointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator1> & lhs, const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator1> & lhs, const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/AddWaypointResponse";
  }

  static const char* value(const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success                        # Indicate successful run of triggered service\n"
"string message                      # Informational, e.g. for error messages\n"
;
  }

  static const char* value(const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddWaypointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::AddWaypointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::AddWaypointResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_ADDWAYPOINTRESPONSE_H
