// Generated by gencpp from file rsm_msgs/GetNavigationGoal.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GETNAVIGATIONGOAL_H
#define RSM_MSGS_MESSAGE_GETNAVIGATIONGOAL_H

#include <ros/service_traits.h>


#include <rsm_msgs/GetNavigationGoalRequest.h>
#include <rsm_msgs/GetNavigationGoalResponse.h>


namespace rsm_msgs
{

struct GetNavigationGoal
{

typedef GetNavigationGoalRequest Request;
typedef GetNavigationGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNavigationGoal
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::GetNavigationGoal > {
  static const char* value()
  {
    return "a8db7cf04440217a23ad35e776985384";
  }

  static const char* value(const ::rsm_msgs::GetNavigationGoal&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::GetNavigationGoal > {
  static const char* value()
  {
    return "rsm_msgs/GetNavigationGoal";
  }

  static const char* value(const ::rsm_msgs::GetNavigationGoal&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::GetNavigationGoalRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::GetNavigationGoal >
template<>
struct MD5Sum< ::rsm_msgs::GetNavigationGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::GetNavigationGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetNavigationGoalRequest> should match
// service_traits::DataType< ::rsm_msgs::GetNavigationGoal >
template<>
struct DataType< ::rsm_msgs::GetNavigationGoalRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::GetNavigationGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::GetNavigationGoalResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::GetNavigationGoal >
template<>
struct MD5Sum< ::rsm_msgs::GetNavigationGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::GetNavigationGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetNavigationGoalResponse> should match
// service_traits::DataType< ::rsm_msgs::GetNavigationGoal >
template<>
struct DataType< ::rsm_msgs::GetNavigationGoalResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::GetNavigationGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GETNAVIGATIONGOAL_H
