// Generated by gencpp from file rsm_msgs/GetRobotPose.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GETROBOTPOSE_H
#define RSM_MSGS_MESSAGE_GETROBOTPOSE_H

#include <ros/service_traits.h>


#include <rsm_msgs/GetRobotPoseRequest.h>
#include <rsm_msgs/GetRobotPoseResponse.h>


namespace rsm_msgs
{

struct GetRobotPose
{

typedef GetRobotPoseRequest Request;
typedef GetRobotPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRobotPose
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::GetRobotPose > {
  static const char* value()
  {
    return "f192399f711a48924df9a394d37edd67";
  }

  static const char* value(const ::rsm_msgs::GetRobotPose&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::GetRobotPose > {
  static const char* value()
  {
    return "rsm_msgs/GetRobotPose";
  }

  static const char* value(const ::rsm_msgs::GetRobotPose&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::GetRobotPoseRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::GetRobotPose >
template<>
struct MD5Sum< ::rsm_msgs::GetRobotPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::rsm_msgs::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetRobotPoseRequest> should match
// service_traits::DataType< ::rsm_msgs::GetRobotPose >
template<>
struct DataType< ::rsm_msgs::GetRobotPoseRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::rsm_msgs::GetRobotPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::GetRobotPoseResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::GetRobotPose >
template<>
struct MD5Sum< ::rsm_msgs::GetRobotPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::rsm_msgs::GetRobotPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetRobotPoseResponse> should match
// service_traits::DataType< ::rsm_msgs::GetRobotPose >
template<>
struct DataType< ::rsm_msgs::GetRobotPoseResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetRobotPose >::value();
  }
  static const char* value(const ::rsm_msgs::GetRobotPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GETROBOTPOSE_H
