// Generated by gencpp from file rsm_msgs/GetWaypoints.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GETWAYPOINTS_H
#define RSM_MSGS_MESSAGE_GETWAYPOINTS_H

#include <ros/service_traits.h>


#include <rsm_msgs/GetWaypointsRequest.h>
#include <rsm_msgs/GetWaypointsResponse.h>


namespace rsm_msgs
{

struct GetWaypoints
{

typedef GetWaypointsRequest Request;
typedef GetWaypointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypoints
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::GetWaypoints > {
  static const char* value()
  {
    return "ea0a0717f7375d28edf3c4cefe8095da";
  }

  static const char* value(const ::rsm_msgs::GetWaypoints&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::GetWaypoints > {
  static const char* value()
  {
    return "rsm_msgs/GetWaypoints";
  }

  static const char* value(const ::rsm_msgs::GetWaypoints&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::GetWaypointsRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::GetWaypoints >
template<>
struct MD5Sum< ::rsm_msgs::GetWaypointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetWaypointsRequest> should match
// service_traits::DataType< ::rsm_msgs::GetWaypoints >
template<>
struct DataType< ::rsm_msgs::GetWaypointsRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::GetWaypointsResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::GetWaypoints >
template<>
struct MD5Sum< ::rsm_msgs::GetWaypointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetWaypointsResponse> should match
// service_traits::DataType< ::rsm_msgs::GetWaypoints >
template<>
struct DataType< ::rsm_msgs::GetWaypointsResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetWaypoints >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GETWAYPOINTS_H
