// Generated by gencpp from file rsm_msgs/GetWaypointRoutinesResponse.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GETWAYPOINTROUTINESRESPONSE_H
#define RSM_MSGS_MESSAGE_GETWAYPOINTROUTINESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsm_msgs
{
template <class ContainerAllocator>
struct GetWaypointRoutinesResponse_
{
  typedef GetWaypointRoutinesResponse_<ContainerAllocator> Type;

  GetWaypointRoutinesResponse_()
    : waypointRoutines()  {
    }
  GetWaypointRoutinesResponse_(const ContainerAllocator& _alloc)
    : waypointRoutines(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _waypointRoutines_type;
  _waypointRoutines_type waypointRoutines;





  typedef boost::shared_ptr< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWaypointRoutinesResponse_

typedef ::rsm_msgs::GetWaypointRoutinesResponse_<std::allocator<void> > GetWaypointRoutinesResponse;

typedef boost::shared_ptr< ::rsm_msgs::GetWaypointRoutinesResponse > GetWaypointRoutinesResponsePtr;
typedef boost::shared_ptr< ::rsm_msgs::GetWaypointRoutinesResponse const> GetWaypointRoutinesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator1> & lhs, const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.waypointRoutines == rhs.waypointRoutines;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator1> & lhs, const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b220fb1d6a56e5ac72aec59f32a9bf6";
  }

  static const char* value(const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b220fb1d6a56e5aULL;
  static const uint64_t static_value2 = 0xc72aec59f32a9bf6ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/GetWaypointRoutinesResponse";
  }

  static const char* value(const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] waypointRoutines		   		# Array of all waypoint routines available\n"
"\n"
;
  }

  static const char* value(const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypointRoutines);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWaypointRoutinesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::GetWaypointRoutinesResponse_<ContainerAllocator>& v)
  {
    s << indent << "waypointRoutines[]" << std::endl;
    for (size_t i = 0; i < v.waypointRoutines.size(); ++i)
    {
      s << indent << "  waypointRoutines[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.waypointRoutines[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GETWAYPOINTROUTINESRESPONSE_H
