// Generated by gencpp from file rsm_msgs/GetWaypointRoutines.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GETWAYPOINTROUTINES_H
#define RSM_MSGS_MESSAGE_GETWAYPOINTROUTINES_H

#include <ros/service_traits.h>


#include <rsm_msgs/GetWaypointRoutinesRequest.h>
#include <rsm_msgs/GetWaypointRoutinesResponse.h>


namespace rsm_msgs
{

struct GetWaypointRoutines
{

typedef GetWaypointRoutinesRequest Request;
typedef GetWaypointRoutinesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetWaypointRoutines
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::GetWaypointRoutines > {
  static const char* value()
  {
    return "2b220fb1d6a56e5ac72aec59f32a9bf6";
  }

  static const char* value(const ::rsm_msgs::GetWaypointRoutines&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::GetWaypointRoutines > {
  static const char* value()
  {
    return "rsm_msgs/GetWaypointRoutines";
  }

  static const char* value(const ::rsm_msgs::GetWaypointRoutines&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::GetWaypointRoutinesRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::GetWaypointRoutines >
template<>
struct MD5Sum< ::rsm_msgs::GetWaypointRoutinesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetWaypointRoutines >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointRoutinesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetWaypointRoutinesRequest> should match
// service_traits::DataType< ::rsm_msgs::GetWaypointRoutines >
template<>
struct DataType< ::rsm_msgs::GetWaypointRoutinesRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetWaypointRoutines >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointRoutinesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::GetWaypointRoutinesResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::GetWaypointRoutines >
template<>
struct MD5Sum< ::rsm_msgs::GetWaypointRoutinesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GetWaypointRoutines >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointRoutinesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GetWaypointRoutinesResponse> should match
// service_traits::DataType< ::rsm_msgs::GetWaypointRoutines >
template<>
struct DataType< ::rsm_msgs::GetWaypointRoutinesResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GetWaypointRoutines >::value();
  }
  static const char* value(const ::rsm_msgs::GetWaypointRoutinesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GETWAYPOINTROUTINES_H
