// Generated by gencpp from file rsm_msgs/GetWaypointsRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GETWAYPOINTSREQUEST_H
#define RSM_MSGS_MESSAGE_GETWAYPOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsm_msgs
{
template <class ContainerAllocator>
struct GetWaypointsRequest_
{
  typedef GetWaypointsRequest_<ContainerAllocator> Type;

  GetWaypointsRequest_()
    {
    }
  GetWaypointsRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetWaypointsRequest_

typedef ::rsm_msgs::GetWaypointsRequest_<std::allocator<void> > GetWaypointsRequest;

typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsRequest > GetWaypointsRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsRequest const> GetWaypointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/GetWaypointsRequest";
  }

  static const char* value(const ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWaypointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rsm_msgs::GetWaypointsRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GETWAYPOINTSREQUEST_H
