// Generated by gencpp from file rsm_msgs/GetWaypointsResponse.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GETWAYPOINTSRESPONSE_H
#define RSM_MSGS_MESSAGE_GETWAYPOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rsm_msgs/WaypointArray.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct GetWaypointsResponse_
{
  typedef GetWaypointsResponse_<ContainerAllocator> Type;

  GetWaypointsResponse_()
    : waypointArray()  {
    }
  GetWaypointsResponse_(const ContainerAllocator& _alloc)
    : waypointArray(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rsm_msgs::WaypointArray_<ContainerAllocator>  _waypointArray_type;
  _waypointArray_type waypointArray;





  typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWaypointsResponse_

typedef ::rsm_msgs::GetWaypointsResponse_<std::allocator<void> > GetWaypointsResponse;

typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsResponse > GetWaypointsResponsePtr;
typedef boost::shared_ptr< ::rsm_msgs::GetWaypointsResponse const> GetWaypointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator1> & lhs, const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.waypointArray == rhs.waypointArray;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator1> & lhs, const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea0a0717f7375d28edf3c4cefe8095da";
  }

  static const char* value(const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea0a0717f7375d28ULL;
  static const uint64_t static_value2 = 0xedf3c4cefe8095daULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/GetWaypointsResponse";
  }

  static const char* value(const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/WaypointArray waypointArray   # Array of all waypoints\n"
"\n"
"\n"
"================================================================================\n"
"MSG: rsm_msgs/WaypointArray\n"
"# Describes an array of waypoints to follow\n"
"std_msgs/Header header\n"
"string ns\n"
"\n"
"uint8 mode              # Waypoint following mode\n"
"\n"
"uint8 SINGLE = 0        # Single trip from start to end\n"
"uint8 ROUNDTRIP = 1     # Drive from start to end then to start again and repeat\n"
"uint8 PATROL = 2        # Drive from start to end then in reverse and repeat\n"
"\n"
"bool reverse            # Driving from start to end (=false) or end to start (=true)\n"
"\n"
"Waypoint[] waypoints    # Array of all waypoints for following\n"
"int32 waypoints_size     # Number of waypoints in the waypoint array\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rsm_msgs/Waypoint\n"
"#A waypoint for waypoint following\n"
"geometry_msgs/Pose pose     # Pose of this waypoint\n"
"bool visited                # True if the waypoint was already visited\n"
"bool unreachable			# True if no path to this waypoint could be found\n"
"string routine				# Routine to be executed on reaching waypoint\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypointArray);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWaypointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::GetWaypointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "waypointArray: ";
    s << std::endl;
    Printer< ::rsm_msgs::WaypointArray_<ContainerAllocator> >::stream(s, indent + "  ", v.waypointArray);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GETWAYPOINTSRESPONSE_H
