// Generated by gencpp from file rsm_msgs/GoalCompletedRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GOALCOMPLETEDREQUEST_H
#define RSM_MSGS_MESSAGE_GOALCOMPLETEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rsm_msgs/GoalStatus.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct GoalCompletedRequest_
{
  typedef GoalCompletedRequest_<ContainerAllocator> Type;

  GoalCompletedRequest_()
    : status()  {
    }
  GoalCompletedRequest_(const ContainerAllocator& _alloc)
    : status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rsm_msgs::GoalStatus_<ContainerAllocator>  _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GoalCompletedRequest_

typedef ::rsm_msgs::GoalCompletedRequest_<std::allocator<void> > GoalCompletedRequest;

typedef boost::shared_ptr< ::rsm_msgs::GoalCompletedRequest > GoalCompletedRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::GoalCompletedRequest const> GoalCompletedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab442b23c0f408235e52225f26a4a743";
  }

  static const char* value(const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab442b23c0f40823ULL;
  static const uint64_t static_value2 = 0x5e52225f26a4a743ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/GoalCompletedRequest";
  }

  static const char* value(const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/GoalStatus status			# Goal status\n"
"\n"
"================================================================================\n"
"MSG: rsm_msgs/GoalStatus\n"
"#Information about currently active goal\n"
"geometry_msgs/Pose goal			 	# Goal in the map\n"
"uint8 goal_status					# Status of the goal \n"
"\n"
"uint8 ACTIVE = 0       				# Goal is still active\n"
"uint8 REACHED = 1       			# Goal was successfully reached\n"
"uint8 FAILED = 2        			# Failed to reach goal\n"
"uint8 ABORTED = 3        			# Aborted goal before completion\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalCompletedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::GoalCompletedRequest_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    s << std::endl;
    Printer< ::rsm_msgs::GoalStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GOALCOMPLETEDREQUEST_H
