// Generated by gencpp from file rsm_msgs/GoalCompleted.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GOALCOMPLETED_H
#define RSM_MSGS_MESSAGE_GOALCOMPLETED_H

#include <ros/service_traits.h>


#include <rsm_msgs/GoalCompletedRequest.h>
#include <rsm_msgs/GoalCompletedResponse.h>


namespace rsm_msgs
{

struct GoalCompleted
{

typedef GoalCompletedRequest Request;
typedef GoalCompletedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalCompleted
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::GoalCompleted > {
  static const char* value()
  {
    return "a69cf0e7e0685d899e584ceb18804a9e";
  }

  static const char* value(const ::rsm_msgs::GoalCompleted&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::GoalCompleted > {
  static const char* value()
  {
    return "rsm_msgs/GoalCompleted";
  }

  static const char* value(const ::rsm_msgs::GoalCompleted&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::GoalCompletedRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::GoalCompleted >
template<>
struct MD5Sum< ::rsm_msgs::GoalCompletedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GoalCompleted >::value();
  }
  static const char* value(const ::rsm_msgs::GoalCompletedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GoalCompletedRequest> should match
// service_traits::DataType< ::rsm_msgs::GoalCompleted >
template<>
struct DataType< ::rsm_msgs::GoalCompletedRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GoalCompleted >::value();
  }
  static const char* value(const ::rsm_msgs::GoalCompletedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::GoalCompletedResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::GoalCompleted >
template<>
struct MD5Sum< ::rsm_msgs::GoalCompletedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::GoalCompleted >::value();
  }
  static const char* value(const ::rsm_msgs::GoalCompletedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::GoalCompletedResponse> should match
// service_traits::DataType< ::rsm_msgs::GoalCompleted >
template<>
struct DataType< ::rsm_msgs::GoalCompletedResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::GoalCompleted >::value();
  }
  static const char* value(const ::rsm_msgs::GoalCompletedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GOALCOMPLETED_H
