// Generated by gencpp from file rsm_msgs/GoalStatus.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_GOALSTATUS_H
#define RSM_MSGS_MESSAGE_GOALSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct GoalStatus_
{
  typedef GoalStatus_<ContainerAllocator> Type;

  GoalStatus_()
    : goal()
    , goal_status(0)  {
    }
  GoalStatus_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , goal_status(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef uint8_t _goal_status_type;
  _goal_status_type goal_status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(ACTIVE)
  #undef ACTIVE
#endif
#if defined(_WIN32) && defined(REACHED)
  #undef REACHED
#endif
#if defined(_WIN32) && defined(FAILED)
  #undef FAILED
#endif
#if defined(_WIN32) && defined(ABORTED)
  #undef ABORTED
#endif

  enum {
    ACTIVE = 0u,
    REACHED = 1u,
    FAILED = 2u,
    ABORTED = 3u,
  };


  typedef boost::shared_ptr< ::rsm_msgs::GoalStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::GoalStatus_<ContainerAllocator> const> ConstPtr;

}; // struct GoalStatus_

typedef ::rsm_msgs::GoalStatus_<std::allocator<void> > GoalStatus;

typedef boost::shared_ptr< ::rsm_msgs::GoalStatus > GoalStatusPtr;
typedef boost::shared_ptr< ::rsm_msgs::GoalStatus const> GoalStatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::GoalStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::GoalStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::GoalStatus_<ContainerAllocator1> & lhs, const ::rsm_msgs::GoalStatus_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal &&
    lhs.goal_status == rhs.goal_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::GoalStatus_<ContainerAllocator1> & lhs, const ::rsm_msgs::GoalStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::GoalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::GoalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::GoalStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d846ca20fc8170d57b2d738bb5885a3e";
  }

  static const char* value(const ::rsm_msgs::GoalStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd846ca20fc8170d5ULL;
  static const uint64_t static_value2 = 0x7b2d738bb5885a3eULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/GoalStatus";
  }

  static const char* value(const ::rsm_msgs::GoalStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Information about currently active goal\n"
"geometry_msgs/Pose goal			 	# Goal in the map\n"
"uint8 goal_status					# Status of the goal \n"
"\n"
"uint8 ACTIVE = 0       				# Goal is still active\n"
"uint8 REACHED = 1       			# Goal was successfully reached\n"
"uint8 FAILED = 2        			# Failed to reach goal\n"
"uint8 ABORTED = 3        			# Aborted goal before completion\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::GoalStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.goal_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::GoalStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::GoalStatus_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "goal_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.goal_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_GOALSTATUS_H
