// Generated by gencpp from file rsm_msgs/MoveWaypoint.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_MOVEWAYPOINT_H
#define RSM_MSGS_MESSAGE_MOVEWAYPOINT_H

#include <ros/service_traits.h>


#include <rsm_msgs/MoveWaypointRequest.h>
#include <rsm_msgs/MoveWaypointResponse.h>


namespace rsm_msgs
{

struct MoveWaypoint
{

typedef MoveWaypointRequest Request;
typedef MoveWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveWaypoint
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::MoveWaypoint > {
  static const char* value()
  {
    return "2707257014f8d83c4fab3f5f2f35968a";
  }

  static const char* value(const ::rsm_msgs::MoveWaypoint&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::MoveWaypoint > {
  static const char* value()
  {
    return "rsm_msgs/MoveWaypoint";
  }

  static const char* value(const ::rsm_msgs::MoveWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::MoveWaypointRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::MoveWaypoint >
template<>
struct MD5Sum< ::rsm_msgs::MoveWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::MoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::MoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::MoveWaypointRequest> should match
// service_traits::DataType< ::rsm_msgs::MoveWaypoint >
template<>
struct DataType< ::rsm_msgs::MoveWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::MoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::MoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::MoveWaypointResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::MoveWaypoint >
template<>
struct MD5Sum< ::rsm_msgs::MoveWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::MoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::MoveWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::MoveWaypointResponse> should match
// service_traits::DataType< ::rsm_msgs::MoveWaypoint >
template<>
struct DataType< ::rsm_msgs::MoveWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::MoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::MoveWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_MOVEWAYPOINT_H
