// Generated by gencpp from file rsm_msgs/MoveWaypointRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_MOVEWAYPOINTREQUEST_H
#define RSM_MSGS_MESSAGE_MOVEWAYPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct MoveWaypointRequest_
{
  typedef MoveWaypointRequest_<ContainerAllocator> Type;

  MoveWaypointRequest_()
    : position(0)
    , pose()  {
    }
  MoveWaypointRequest_(const ContainerAllocator& _alloc)
    : position(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveWaypointRequest_

typedef ::rsm_msgs::MoveWaypointRequest_<std::allocator<void> > MoveWaypointRequest;

typedef boost::shared_ptr< ::rsm_msgs::MoveWaypointRequest > MoveWaypointRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::MoveWaypointRequest const> MoveWaypointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8c9217b4d2fe5f9b972d9c69290efea";
  }

  static const char* value(const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8c9217b4d2fe5f9ULL;
  static const uint64_t static_value2 = 0xb972d9c69290efeaULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/MoveWaypointRequest";
  }

  static const char* value(const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 position                      # Position in array of waypoint to be moved\n"
"geometry_msgs/Pose pose				# New pose of the waypoint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveWaypointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::MoveWaypointRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_MOVEWAYPOINTREQUEST_H
