// Generated by gencpp from file rsm_msgs/OperationMode.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_OPERATIONMODE_H
#define RSM_MSGS_MESSAGE_OPERATIONMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsm_msgs
{
template <class ContainerAllocator>
struct OperationMode_
{
  typedef OperationMode_<ContainerAllocator> Type;

  OperationMode_()
    : emergencyStop(false)
    , mode(0)  {
    }
  OperationMode_(const ContainerAllocator& _alloc)
    : emergencyStop(false)
    , mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _emergencyStop_type;
  _emergencyStop_type emergencyStop;

   typedef uint8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STOPPED)
  #undef STOPPED
#endif
#if defined(_WIN32) && defined(AUTONOMOUS)
  #undef AUTONOMOUS
#endif
#if defined(_WIN32) && defined(TELEOPERATION)
  #undef TELEOPERATION
#endif

  enum {
    STOPPED = 0u,
    AUTONOMOUS = 1u,
    TELEOPERATION = 2u,
  };


  typedef boost::shared_ptr< ::rsm_msgs::OperationMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::OperationMode_<ContainerAllocator> const> ConstPtr;

}; // struct OperationMode_

typedef ::rsm_msgs::OperationMode_<std::allocator<void> > OperationMode;

typedef boost::shared_ptr< ::rsm_msgs::OperationMode > OperationModePtr;
typedef boost::shared_ptr< ::rsm_msgs::OperationMode const> OperationModeConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::OperationMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::OperationMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::OperationMode_<ContainerAllocator1> & lhs, const ::rsm_msgs::OperationMode_<ContainerAllocator2> & rhs)
{
  return lhs.emergencyStop == rhs.emergencyStop &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::OperationMode_<ContainerAllocator1> & lhs, const ::rsm_msgs::OperationMode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::OperationMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::OperationMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::OperationMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::OperationMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::OperationMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::OperationMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::OperationMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a2b892239d01889665a0278d874ed60";
  }

  static const char* value(const ::rsm_msgs::OperationMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a2b892239d01889ULL;
  static const uint64_t static_value2 = 0x665a0278d874ed60ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::OperationMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/OperationMode";
  }

  static const char* value(const ::rsm_msgs::OperationMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::OperationMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Operation mode including information about emergency stop\n"
"bool emergencyStop					# Is emergency stop activated\n"
"\n"
"uint8 STOPPED = 0        			# Robot is stopped\n"
"uint8 AUTONOMOUS = 1     			# Robot is controlled by the autonomy cmd vel topic	\n"
"uint8 TELEOPERATION = 2        		# Robot is controlled by the teleoperation cmd vel topic	\n"
"\n"
"uint8 mode							# Operation mode\n"
;
  }

  static const char* value(const ::rsm_msgs::OperationMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::OperationMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.emergencyStop);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OperationMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::OperationMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::OperationMode_<ContainerAllocator>& v)
  {
    s << indent << "emergencyStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergencyStop);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_OPERATIONMODE_H
