// Generated by gencpp from file rsm_msgs/RemoveWaypoint.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_REMOVEWAYPOINT_H
#define RSM_MSGS_MESSAGE_REMOVEWAYPOINT_H

#include <ros/service_traits.h>


#include <rsm_msgs/RemoveWaypointRequest.h>
#include <rsm_msgs/RemoveWaypointResponse.h>


namespace rsm_msgs
{

struct RemoveWaypoint
{

typedef RemoveWaypointRequest Request;
typedef RemoveWaypointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RemoveWaypoint
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "3e07da95f3577b8955e235d4863c62b0";
  }

  static const char* value(const ::rsm_msgs::RemoveWaypoint&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::RemoveWaypoint > {
  static const char* value()
  {
    return "rsm_msgs/RemoveWaypoint";
  }

  static const char* value(const ::rsm_msgs::RemoveWaypoint&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::RemoveWaypointRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::RemoveWaypoint >
template<>
struct MD5Sum< ::rsm_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::RemoveWaypointRequest> should match
// service_traits::DataType< ::rsm_msgs::RemoveWaypoint >
template<>
struct DataType< ::rsm_msgs::RemoveWaypointRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::RemoveWaypointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::RemoveWaypointResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::RemoveWaypoint >
template<>
struct MD5Sum< ::rsm_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::RemoveWaypointResponse> should match
// service_traits::DataType< ::rsm_msgs::RemoveWaypoint >
template<>
struct DataType< ::rsm_msgs::RemoveWaypointResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::RemoveWaypoint >::value();
  }
  static const char* value(const ::rsm_msgs::RemoveWaypointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_REMOVEWAYPOINT_H
