// Generated by gencpp from file rsm_msgs/SetNavigationGoal.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETNAVIGATIONGOAL_H
#define RSM_MSGS_MESSAGE_SETNAVIGATIONGOAL_H

#include <ros/service_traits.h>


#include <rsm_msgs/SetNavigationGoalRequest.h>
#include <rsm_msgs/SetNavigationGoalResponse.h>


namespace rsm_msgs
{

struct SetNavigationGoal
{

typedef SetNavigationGoalRequest Request;
typedef SetNavigationGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetNavigationGoal
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::SetNavigationGoal > {
  static const char* value()
  {
    return "7f219f0d367008b829d419b8dccf0d16";
  }

  static const char* value(const ::rsm_msgs::SetNavigationGoal&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::SetNavigationGoal > {
  static const char* value()
  {
    return "rsm_msgs/SetNavigationGoal";
  }

  static const char* value(const ::rsm_msgs::SetNavigationGoal&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::SetNavigationGoalRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::SetNavigationGoal >
template<>
struct MD5Sum< ::rsm_msgs::SetNavigationGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::SetNavigationGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetNavigationGoalRequest> should match
// service_traits::DataType< ::rsm_msgs::SetNavigationGoal >
template<>
struct DataType< ::rsm_msgs::SetNavigationGoalRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::SetNavigationGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::SetNavigationGoalResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::SetNavigationGoal >
template<>
struct MD5Sum< ::rsm_msgs::SetNavigationGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::SetNavigationGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetNavigationGoalResponse> should match
// service_traits::DataType< ::rsm_msgs::SetNavigationGoal >
template<>
struct DataType< ::rsm_msgs::SetNavigationGoalResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetNavigationGoal >::value();
  }
  static const char* value(const ::rsm_msgs::SetNavigationGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETNAVIGATIONGOAL_H
