// Generated by gencpp from file rsm_msgs/SetNavigationGoalRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETNAVIGATIONGOALREQUEST_H
#define RSM_MSGS_MESSAGE_SETNAVIGATIONGOALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct SetNavigationGoalRequest_
{
  typedef SetNavigationGoalRequest_<ContainerAllocator> Type;

  SetNavigationGoalRequest_()
    : goal()
    , navigationMode(0)
    , waypointPosition(0)
    , routine()  {
    }
  SetNavigationGoalRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , navigationMode(0)
    , waypointPosition(0)
    , routine(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef int8_t _navigationMode_type;
  _navigationMode_type navigationMode;

   typedef int64_t _waypointPosition_type;
  _waypointPosition_type waypointPosition;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _routine_type;
  _routine_type routine;





  typedef boost::shared_ptr< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetNavigationGoalRequest_

typedef ::rsm_msgs::SetNavigationGoalRequest_<std::allocator<void> > SetNavigationGoalRequest;

typedef boost::shared_ptr< ::rsm_msgs::SetNavigationGoalRequest > SetNavigationGoalRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::SetNavigationGoalRequest const> SetNavigationGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal &&
    lhs.navigationMode == rhs.navigationMode &&
    lhs.waypointPosition == rhs.waypointPosition &&
    lhs.routine == rhs.routine;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8db7cf04440217a23ad35e776985384";
  }

  static const char* value(const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8db7cf04440217aULL;
  static const uint64_t static_value2 = 0x23ad35e776985384ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/SetNavigationGoalRequest";
  }

  static const char* value(const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose goal 			# Goal for navigation\n"
"int8 navigationMode					# Mode of navigation (Exploration=0, Waypoint following=1 and Simple Goal=2)\n"
"int64 waypointPosition				# Position of waypoint in array\n"
"string routine						# Routine plugin name to be executed at waypoint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.navigationMode);
      stream.next(m.waypointPosition);
      stream.next(m.routine);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNavigationGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::SetNavigationGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "navigationMode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.navigationMode);
    s << indent << "waypointPosition: ";
    Printer<int64_t>::stream(s, indent + "  ", v.waypointPosition);
    s << indent << "routine: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.routine);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETNAVIGATIONGOALREQUEST_H
