// Generated by gencpp from file rsm_msgs/SetOperationMode.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETOPERATIONMODE_H
#define RSM_MSGS_MESSAGE_SETOPERATIONMODE_H

#include <ros/service_traits.h>


#include <rsm_msgs/SetOperationModeRequest.h>
#include <rsm_msgs/SetOperationModeResponse.h>


namespace rsm_msgs
{

struct SetOperationMode
{

typedef SetOperationModeRequest Request;
typedef SetOperationModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOperationMode
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::SetOperationMode > {
  static const char* value()
  {
    return "2760717e8c5a5aefc48015322fde6db7";
  }

  static const char* value(const ::rsm_msgs::SetOperationMode&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::SetOperationMode > {
  static const char* value()
  {
    return "rsm_msgs/SetOperationMode";
  }

  static const char* value(const ::rsm_msgs::SetOperationMode&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::SetOperationModeRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::SetOperationMode >
template<>
struct MD5Sum< ::rsm_msgs::SetOperationModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetOperationMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetOperationModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetOperationModeRequest> should match
// service_traits::DataType< ::rsm_msgs::SetOperationMode >
template<>
struct DataType< ::rsm_msgs::SetOperationModeRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetOperationMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetOperationModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::SetOperationModeResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::SetOperationMode >
template<>
struct MD5Sum< ::rsm_msgs::SetOperationModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetOperationMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetOperationModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetOperationModeResponse> should match
// service_traits::DataType< ::rsm_msgs::SetOperationMode >
template<>
struct DataType< ::rsm_msgs::SetOperationModeResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetOperationMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetOperationModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETOPERATIONMODE_H
