// Generated by gencpp from file rsm_msgs/SetOperationModeRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETOPERATIONMODEREQUEST_H
#define RSM_MSGS_MESSAGE_SETOPERATIONMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rsm_msgs/OperationMode.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct SetOperationModeRequest_
{
  typedef SetOperationModeRequest_<ContainerAllocator> Type;

  SetOperationModeRequest_()
    : operationMode()  {
    }
  SetOperationModeRequest_(const ContainerAllocator& _alloc)
    : operationMode(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rsm_msgs::OperationMode_<ContainerAllocator>  _operationMode_type;
  _operationMode_type operationMode;





  typedef boost::shared_ptr< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetOperationModeRequest_

typedef ::rsm_msgs::SetOperationModeRequest_<std::allocator<void> > SetOperationModeRequest;

typedef boost::shared_ptr< ::rsm_msgs::SetOperationModeRequest > SetOperationModeRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::SetOperationModeRequest const> SetOperationModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.operationMode == rhs.operationMode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "206b56495b7cd2db2bc1b917c72501e5";
  }

  static const char* value(const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x206b56495b7cd2dbULL;
  static const uint64_t static_value2 = 0x2bc1b917c72501e5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/SetOperationModeRequest";
  }

  static const char* value(const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/OperationMode operationMode	#Info about operation mode including emergency stop\n"
"\n"
"================================================================================\n"
"MSG: rsm_msgs/OperationMode\n"
"#Operation mode including information about emergency stop\n"
"bool emergencyStop					# Is emergency stop activated\n"
"\n"
"uint8 STOPPED = 0        			# Robot is stopped\n"
"uint8 AUTONOMOUS = 1     			# Robot is controlled by the autonomy cmd vel topic	\n"
"uint8 TELEOPERATION = 2        		# Robot is controlled by the teleoperation cmd vel topic	\n"
"\n"
"uint8 mode							# Operation mode\n"
;
  }

  static const char* value(const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.operationMode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetOperationModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::SetOperationModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "operationMode: ";
    s << std::endl;
    Printer< ::rsm_msgs::OperationMode_<ContainerAllocator> >::stream(s, indent + "  ", v.operationMode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETOPERATIONMODEREQUEST_H
