// Generated by gencpp from file rsm_msgs/SetWaypointFollowingMode.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETWAYPOINTFOLLOWINGMODE_H
#define RSM_MSGS_MESSAGE_SETWAYPOINTFOLLOWINGMODE_H

#include <ros/service_traits.h>


#include <rsm_msgs/SetWaypointFollowingModeRequest.h>
#include <rsm_msgs/SetWaypointFollowingModeResponse.h>


namespace rsm_msgs
{

struct SetWaypointFollowingMode
{

typedef SetWaypointFollowingModeRequest Request;
typedef SetWaypointFollowingModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWaypointFollowingMode
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::SetWaypointFollowingMode > {
  static const char* value()
  {
    return "0d60594389c7f5a48533157b5965fc0d";
  }

  static const char* value(const ::rsm_msgs::SetWaypointFollowingMode&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::SetWaypointFollowingMode > {
  static const char* value()
  {
    return "rsm_msgs/SetWaypointFollowingMode";
  }

  static const char* value(const ::rsm_msgs::SetWaypointFollowingMode&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::SetWaypointFollowingModeRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::SetWaypointFollowingMode >
template<>
struct MD5Sum< ::rsm_msgs::SetWaypointFollowingModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetWaypointFollowingMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointFollowingModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetWaypointFollowingModeRequest> should match
// service_traits::DataType< ::rsm_msgs::SetWaypointFollowingMode >
template<>
struct DataType< ::rsm_msgs::SetWaypointFollowingModeRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetWaypointFollowingMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointFollowingModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::SetWaypointFollowingModeResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::SetWaypointFollowingMode >
template<>
struct MD5Sum< ::rsm_msgs::SetWaypointFollowingModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetWaypointFollowingMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointFollowingModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetWaypointFollowingModeResponse> should match
// service_traits::DataType< ::rsm_msgs::SetWaypointFollowingMode >
template<>
struct DataType< ::rsm_msgs::SetWaypointFollowingModeResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetWaypointFollowingMode >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointFollowingModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETWAYPOINTFOLLOWINGMODE_H
