// Generated by gencpp from file rsm_msgs/SetWaypointFollowingModeRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETWAYPOINTFOLLOWINGMODEREQUEST_H
#define RSM_MSGS_MESSAGE_SETWAYPOINTFOLLOWINGMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsm_msgs
{
template <class ContainerAllocator>
struct SetWaypointFollowingModeRequest_
{
  typedef SetWaypointFollowingModeRequest_<ContainerAllocator> Type;

  SetWaypointFollowingModeRequest_()
    : mode(0)
    , reverse(false)  {
    }
  SetWaypointFollowingModeRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , reverse(false)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _reverse_type;
  _reverse_type reverse;





  typedef boost::shared_ptr< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetWaypointFollowingModeRequest_

typedef ::rsm_msgs::SetWaypointFollowingModeRequest_<std::allocator<void> > SetWaypointFollowingModeRequest;

typedef boost::shared_ptr< ::rsm_msgs::SetWaypointFollowingModeRequest > SetWaypointFollowingModeRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::SetWaypointFollowingModeRequest const> SetWaypointFollowingModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.reverse == rhs.reverse;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9529787c8c29df8b2de9da5d59c53475";
  }

  static const char* value(const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9529787c8c29df8bULL;
  static const uint64_t static_value2 = 0x2de9da5d59c53475ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/SetWaypointFollowingModeRequest";
  }

  static const char* value(const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode							# Waypoint following mode\n"
"bool reverse						# Driving from start to end (=false) or end to start (=true)\n"
;
  }

  static const char* value(const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.reverse);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWaypointFollowingModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::SetWaypointFollowingModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "reverse: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reverse);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETWAYPOINTFOLLOWINGMODEREQUEST_H
