// Generated by gencpp from file rsm_msgs/SetWaypointRoutineRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETWAYPOINTROUTINEREQUEST_H
#define RSM_MSGS_MESSAGE_SETWAYPOINTROUTINEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsm_msgs
{
template <class ContainerAllocator>
struct SetWaypointRoutineRequest_
{
  typedef SetWaypointRoutineRequest_<ContainerAllocator> Type;

  SetWaypointRoutineRequest_()
    : position(0)
    , routine()  {
    }
  SetWaypointRoutineRequest_(const ContainerAllocator& _alloc)
    : position(0)
    , routine(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _routine_type;
  _routine_type routine;





  typedef boost::shared_ptr< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetWaypointRoutineRequest_

typedef ::rsm_msgs::SetWaypointRoutineRequest_<std::allocator<void> > SetWaypointRoutineRequest;

typedef boost::shared_ptr< ::rsm_msgs::SetWaypointRoutineRequest > SetWaypointRoutineRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::SetWaypointRoutineRequest const> SetWaypointRoutineRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.routine == rhs.routine;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebd05026ef6446f1497656583b7e0135";
  }

  static const char* value(const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebd05026ef6446f1ULL;
  static const uint64_t static_value2 = 0x497656583b7e0135ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/SetWaypointRoutineRequest";
  }

  static const char* value(const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 position                      # Position in array of waypoint to be moved\n"
"string routine						# Waypoint routine\n"
;
  }

  static const char* value(const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.routine);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetWaypointRoutineRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::SetWaypointRoutineRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
    s << indent << "routine: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.routine);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETWAYPOINTROUTINEREQUEST_H
