// Generated by gencpp from file rsm_msgs/SetWaypointRoutine.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_SETWAYPOINTROUTINE_H
#define RSM_MSGS_MESSAGE_SETWAYPOINTROUTINE_H

#include <ros/service_traits.h>


#include <rsm_msgs/SetWaypointRoutineRequest.h>
#include <rsm_msgs/SetWaypointRoutineResponse.h>


namespace rsm_msgs
{

struct SetWaypointRoutine
{

typedef SetWaypointRoutineRequest Request;
typedef SetWaypointRoutineResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetWaypointRoutine
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::SetWaypointRoutine > {
  static const char* value()
  {
    return "6e041540f9d404e36a7461b015bc51aa";
  }

  static const char* value(const ::rsm_msgs::SetWaypointRoutine&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::SetWaypointRoutine > {
  static const char* value()
  {
    return "rsm_msgs/SetWaypointRoutine";
  }

  static const char* value(const ::rsm_msgs::SetWaypointRoutine&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::SetWaypointRoutineRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::SetWaypointRoutine >
template<>
struct MD5Sum< ::rsm_msgs::SetWaypointRoutineRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetWaypointRoutine >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointRoutineRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetWaypointRoutineRequest> should match
// service_traits::DataType< ::rsm_msgs::SetWaypointRoutine >
template<>
struct DataType< ::rsm_msgs::SetWaypointRoutineRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetWaypointRoutine >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointRoutineRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::SetWaypointRoutineResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::SetWaypointRoutine >
template<>
struct MD5Sum< ::rsm_msgs::SetWaypointRoutineResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::SetWaypointRoutine >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointRoutineResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::SetWaypointRoutineResponse> should match
// service_traits::DataType< ::rsm_msgs::SetWaypointRoutine >
template<>
struct DataType< ::rsm_msgs::SetWaypointRoutineResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::SetWaypointRoutine >::value();
  }
  static const char* value(const ::rsm_msgs::SetWaypointRoutineResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_SETWAYPOINTROUTINE_H
