// Generated by gencpp from file rsm_msgs/WaypointArray.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_WAYPOINTARRAY_H
#define RSM_MSGS_MESSAGE_WAYPOINTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <rsm_msgs/Waypoint.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct WaypointArray_
{
  typedef WaypointArray_<ContainerAllocator> Type;

  WaypointArray_()
    : header()
    , ns()
    , mode(0)
    , reverse(false)
    , waypoints()
    , waypoints_size(0)  {
    }
  WaypointArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ns(_alloc)
    , mode(0)
    , reverse(false)
    , waypoints(_alloc)
    , waypoints_size(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ns_type;
  _ns_type ns;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _reverse_type;
  _reverse_type reverse;

   typedef std::vector< ::rsm_msgs::Waypoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rsm_msgs::Waypoint_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;

   typedef int32_t _waypoints_size_type;
  _waypoints_size_type waypoints_size;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SINGLE)
  #undef SINGLE
#endif
#if defined(_WIN32) && defined(ROUNDTRIP)
  #undef ROUNDTRIP
#endif
#if defined(_WIN32) && defined(PATROL)
  #undef PATROL
#endif

  enum {
    SINGLE = 0u,
    ROUNDTRIP = 1u,
    PATROL = 2u,
  };


  typedef boost::shared_ptr< ::rsm_msgs::WaypointArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::WaypointArray_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointArray_

typedef ::rsm_msgs::WaypointArray_<std::allocator<void> > WaypointArray;

typedef boost::shared_ptr< ::rsm_msgs::WaypointArray > WaypointArrayPtr;
typedef boost::shared_ptr< ::rsm_msgs::WaypointArray const> WaypointArrayConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::WaypointArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::WaypointArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::WaypointArray_<ContainerAllocator1> & lhs, const ::rsm_msgs::WaypointArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ns == rhs.ns &&
    lhs.mode == rhs.mode &&
    lhs.reverse == rhs.reverse &&
    lhs.waypoints == rhs.waypoints &&
    lhs.waypoints_size == rhs.waypoints_size;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::WaypointArray_<ContainerAllocator1> & lhs, const ::rsm_msgs::WaypointArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::WaypointArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::WaypointArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::WaypointArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a09542c5f13ea180a4b1ecb5cbd9ab8";
  }

  static const char* value(const ::rsm_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a09542c5f13ea18ULL;
  static const uint64_t static_value2 = 0x0a4b1ecb5cbd9ab8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/WaypointArray";
  }

  static const char* value(const ::rsm_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Describes an array of waypoints to follow\n"
"std_msgs/Header header\n"
"string ns\n"
"\n"
"uint8 mode              # Waypoint following mode\n"
"\n"
"uint8 SINGLE = 0        # Single trip from start to end\n"
"uint8 ROUNDTRIP = 1     # Drive from start to end then to start again and repeat\n"
"uint8 PATROL = 2        # Drive from start to end then in reverse and repeat\n"
"\n"
"bool reverse            # Driving from start to end (=false) or end to start (=true)\n"
"\n"
"Waypoint[] waypoints    # Array of all waypoints for following\n"
"int32 waypoints_size     # Number of waypoints in the waypoint array\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: rsm_msgs/Waypoint\n"
"#A waypoint for waypoint following\n"
"geometry_msgs/Pose pose     # Pose of this waypoint\n"
"bool visited                # True if the waypoint was already visited\n"
"bool unreachable			# True if no path to this waypoint could be found\n"
"string routine				# Routine to be executed on reaching waypoint\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::WaypointArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ns);
      stream.next(m.mode);
      stream.next(m.reverse);
      stream.next(m.waypoints);
      stream.next(m.waypoints_size);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::WaypointArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::WaypointArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ns: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ns);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "reverse: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reverse);
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rsm_msgs::Waypoint_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
    s << indent << "waypoints_size: ";
    Printer<int32_t>::stream(s, indent + "  ", v.waypoints_size);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_WAYPOINTARRAY_H
