// Generated by gencpp from file rsm_msgs/WaypointUnreachable.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_WAYPOINTUNREACHABLE_H
#define RSM_MSGS_MESSAGE_WAYPOINTUNREACHABLE_H

#include <ros/service_traits.h>


#include <rsm_msgs/WaypointUnreachableRequest.h>
#include <rsm_msgs/WaypointUnreachableResponse.h>


namespace rsm_msgs
{

struct WaypointUnreachable
{

typedef WaypointUnreachableRequest Request;
typedef WaypointUnreachableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointUnreachable
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::WaypointUnreachable > {
  static const char* value()
  {
    return "3e07da95f3577b8955e235d4863c62b0";
  }

  static const char* value(const ::rsm_msgs::WaypointUnreachable&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::WaypointUnreachable > {
  static const char* value()
  {
    return "rsm_msgs/WaypointUnreachable";
  }

  static const char* value(const ::rsm_msgs::WaypointUnreachable&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::WaypointUnreachableRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::WaypointUnreachable >
template<>
struct MD5Sum< ::rsm_msgs::WaypointUnreachableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::WaypointUnreachable >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointUnreachableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::WaypointUnreachableRequest> should match
// service_traits::DataType< ::rsm_msgs::WaypointUnreachable >
template<>
struct DataType< ::rsm_msgs::WaypointUnreachableRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::WaypointUnreachable >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointUnreachableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::WaypointUnreachableResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::WaypointUnreachable >
template<>
struct MD5Sum< ::rsm_msgs::WaypointUnreachableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::WaypointUnreachable >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointUnreachableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::WaypointUnreachableResponse> should match
// service_traits::DataType< ::rsm_msgs::WaypointUnreachable >
template<>
struct DataType< ::rsm_msgs::WaypointUnreachableResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::WaypointUnreachable >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointUnreachableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_WAYPOINTUNREACHABLE_H
