// Generated by gencpp from file rsm_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_WAYPOINT_H
#define RSM_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace rsm_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : pose()
    , visited(false)
    , unreachable(false)
    , routine()  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , visited(false)
    , unreachable(false)
    , routine(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _visited_type;
  _visited_type visited;

   typedef uint8_t _unreachable_type;
  _unreachable_type unreachable;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _routine_type;
  _routine_type routine;





  typedef boost::shared_ptr< ::rsm_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::rsm_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::rsm_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::rsm_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::rsm_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.visited == rhs.visited &&
    lhs.unreachable == rhs.unreachable &&
    lhs.routine == rhs.routine;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::Waypoint_<ContainerAllocator1> & lhs, const ::rsm_msgs::Waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7f7105595f3a7bcd97c4dc459c67269";
  }

  static const char* value(const ::rsm_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7f7105595f3a7bcULL;
  static const uint64_t static_value2 = 0xd97c4dc459c67269ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/Waypoint";
  }

  static const char* value(const ::rsm_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#A waypoint for waypoint following\n"
"geometry_msgs/Pose pose     # Pose of this waypoint\n"
"bool visited                # True if the waypoint was already visited\n"
"bool unreachable			# True if no path to this waypoint could be found\n"
"string routine				# Routine to be executed on reaching waypoint\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::rsm_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.visited);
      stream.next(m.unreachable);
      stream.next(m.routine);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "visited: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.visited);
    s << indent << "unreachable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.unreachable);
    s << indent << "routine: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.routine);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_WAYPOINT_H
