// Generated by gencpp from file rsm_msgs/WaypointVisitedRequest.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_WAYPOINTVISITEDREQUEST_H
#define RSM_MSGS_MESSAGE_WAYPOINTVISITEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsm_msgs
{
template <class ContainerAllocator>
struct WaypointVisitedRequest_
{
  typedef WaypointVisitedRequest_<ContainerAllocator> Type;

  WaypointVisitedRequest_()
    : position(0)  {
    }
  WaypointVisitedRequest_(const ContainerAllocator& _alloc)
    : position(0)  {
  (void)_alloc;
    }



   typedef int64_t _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointVisitedRequest_

typedef ::rsm_msgs::WaypointVisitedRequest_<std::allocator<void> > WaypointVisitedRequest;

typedef boost::shared_ptr< ::rsm_msgs::WaypointVisitedRequest > WaypointVisitedRequestPtr;
typedef boost::shared_ptr< ::rsm_msgs::WaypointVisitedRequest const> WaypointVisitedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator1> & lhs, const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rsm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b97bb7ed9a33fb2edbc8c809cbaebf8";
  }

  static const char* value(const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b97bb7ed9a33fb2ULL;
  static const uint64_t static_value2 = 0xedbc8c809cbaebf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsm_msgs/WaypointVisitedRequest";
  }

  static const char* value(const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 position                      # Position in array of unreachable waypoint\n"
;
  }

  static const char* value(const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointVisitedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsm_msgs::WaypointVisitedRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSM_MSGS_MESSAGE_WAYPOINTVISITEDREQUEST_H
