// Generated by gencpp from file rsm_msgs/WaypointVisited.msg
// DO NOT EDIT!


#ifndef RSM_MSGS_MESSAGE_WAYPOINTVISITED_H
#define RSM_MSGS_MESSAGE_WAYPOINTVISITED_H

#include <ros/service_traits.h>


#include <rsm_msgs/WaypointVisitedRequest.h>
#include <rsm_msgs/WaypointVisitedResponse.h>


namespace rsm_msgs
{

struct WaypointVisited
{

typedef WaypointVisitedRequest Request;
typedef WaypointVisitedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WaypointVisited
} // namespace rsm_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsm_msgs::WaypointVisited > {
  static const char* value()
  {
    return "3e07da95f3577b8955e235d4863c62b0";
  }

  static const char* value(const ::rsm_msgs::WaypointVisited&) { return value(); }
};

template<>
struct DataType< ::rsm_msgs::WaypointVisited > {
  static const char* value()
  {
    return "rsm_msgs/WaypointVisited";
  }

  static const char* value(const ::rsm_msgs::WaypointVisited&) { return value(); }
};


// service_traits::MD5Sum< ::rsm_msgs::WaypointVisitedRequest> should match
// service_traits::MD5Sum< ::rsm_msgs::WaypointVisited >
template<>
struct MD5Sum< ::rsm_msgs::WaypointVisitedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::WaypointVisited >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointVisitedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::WaypointVisitedRequest> should match
// service_traits::DataType< ::rsm_msgs::WaypointVisited >
template<>
struct DataType< ::rsm_msgs::WaypointVisitedRequest>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::WaypointVisited >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointVisitedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsm_msgs::WaypointVisitedResponse> should match
// service_traits::MD5Sum< ::rsm_msgs::WaypointVisited >
template<>
struct MD5Sum< ::rsm_msgs::WaypointVisitedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsm_msgs::WaypointVisited >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointVisitedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsm_msgs::WaypointVisitedResponse> should match
// service_traits::DataType< ::rsm_msgs::WaypointVisited >
template<>
struct DataType< ::rsm_msgs::WaypointVisitedResponse>
{
  static const char* value()
  {
    return DataType< ::rsm_msgs::WaypointVisited >::value();
  }
  static const char* value(const ::rsm_msgs::WaypointVisitedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSM_MSGS_MESSAGE_WAYPOINTVISITED_H
